compilers: swap the order of arguments so that sources come first
When they come after the dependencies such as -lm, the compiler errors
out with:

```
/usr/bin/ld: /tmp/cciXtzE9.o: in function `main':
test.c:(.text+0x7): undefined reference to `round'
collect2: error: ld returned 1 exit status
```

as it cannot actually find those symbols anymore.